spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587 # O 465 para SSL si lo prefieres
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true # Usa true para 587, false para 465
      mail.smtp.ssl.trust: smtp.gmail.com # Agrega esta línea si usas SSL

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web: DEBUG
    com.oo2.grupo15: DEBUG
