spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web: DEBUG
    com.oo2.grupo15: DEBUG
